name: Functional Testing
on:
  workflow_dispatch

jobs:
  function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          cd frontend
          npm install
          cd ../backend
          npm install
          cd ../backend
          npm i -g jest

      - name: Build and Test
        run: |
          cd frontend
          npm start
          cd ../backend
          npm start
