name: GitHub_Runner
on:
  push

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm (Backend)
        uses: actions/setup-node@v2
        with:
           node-version: '14'
           run: |
            cd backend
            npm install

      - name: Install Node.js and npm (Frontend)
        uses: actions/setup-node@v2
        with:
           node-version: '14'
           run: |
            cd frontend
            npm install

      - name: Run Backend
        run: |
           cd backend
           npm start

      - name: Run Frontend
        run: |
           cd frontend
           npm start
