name: To-Do Pipeline
on:
  push

jobs:
  Snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Run Snyk on backend
        uses: snyk/actions/node@master
        continue-on-error: true
        with:
          args: --file=./backend/package.json  # Specify the path to the backend package.json
          command: monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk on frontend
        uses: snyk/actions/node@master
        continue-on-error: true
        with:
          args: --file=./frontend/package.json  # Specify the path to the frontend package.json
          command: monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  SonarQube_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        args: --file=./backend/package.json
        npm install
        
    - name: Install dependencies
      run: |
        args: --file=./frontend/package.json
        npm install
        
    - name: Build
      run: |
        args: --file=./backend/package.json
        npm run build

    - name: Build
      run: |
        args: --file=./frontend/package.json
        npm run build

    - name: SonarQube Scan
      run: |
        npm install -g sonarqube-scanner
        sonar-scanner \
          -Dsonar.projectKey=Test-ToDo-123 \
          -Dsonar.host.url=$SONAR_HOST_URL
          -Dsonar.login=$SONAR_TOKEN
