name: To-Do Pipeline
on: push
jobs:
  Snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        with:
          projectPath: Test-ToDo/blob/main/package-lock.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
