name: To-Do Pipeline
on:
  push

jobs:
  Snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Run Snyk on backend
        uses: snyk/actions/node@master
        continue-on-error: true
        with:
          args: --file=./backend/package.json  # Specify the path to the backend package.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

      - name: Run Snyk on frontend
        uses: snyk/actions/node@master
        continue-on-error: true
        with:
          args: --file=./frontend/package.json  # Specify the path to the frontend package.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
